export const LOAD_AVES_SUCCESS = 'LOAD_AVES_SUCCESS'
export const UPDATE_AVE_SUCCESS = 'UPDATE_AVE_SUCCESS'
export const DELETE_AVE_SUCCESS = 'DELETE_AVE_SUCCESS'
export const CREATE_AVE_SUCCESS = 'CREATE_AVE_SUCCESS'

export const LOAD_ZONAS_SUCCESS = 'LOAD_ZONAS_SUCCESS'
